services:
    eulogin.userprovider:
        class: EcPhp\EuLoginBundle\Security\Core\User\EuLoginUserProvider

    ecas.configuration:
        class: EcPhp\Ecas\EcasProperties
        decorates: 'cas.configuration'
        arguments: ['@ecas.configuration.inner', '@request_stack']

    ecas:
        class: EcPhp\Ecas\Ecas
        decorates: 'cas'
        arguments: ['@ecas.inner', '@nyholm.psr7.psr17_factory']
