build:
    image: default-bionic
    nodes:
        php81:
            environment:
                php:
                    version: 8.1
            dependencies:
                before:
                    - pecl install pcov
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            dependencies:
                before:
                    - pecl install pcov
filter:
    paths:
        - 'src/*'

tools:
    external_code_coverage:
        timeout: 600
    php_loc: true
    php_pdepend: true
    php_sim: true
    php_changetracking: true
