cas:
    base_url: https://webgate.ec.europa.eu/cas
    protocol:
        login:
            path: /login
            default_parameters:
                service: cas_bundle_homepage
        serviceValidate:
            path: /serviceValidate
            default_parameters:
                userDetails: "true"
                #pgtUrl: cas_bundle_proxy_callback
        logout:
            path: /logout
            default_parameters:
                service: cas_bundle_homepage
        proxy:
            path: /proxy
        proxyValidate:
            path: /proxyValidate
            default_parameters:
                userDetails: "true"
                #pgtUrl: cas_bundle_proxy_callback
